name: ycflutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: '>=0.11.3+12'
  flutter_webview_plugin: "^0.3.0+2"
  shared_preferences: "^0.4.1"
  json_serializable: "^2.0.0"
  json_annotation: "^2.0.0"
  build_runner: "^1.0.0"
  json_model: "^0.0.2"
  pull_to_refresh: ^1.4.0
  dio: ^2.1.6
  cached_network_image: ^0.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
  - lib/image/ic_launcher_round.png
  - lib/image/zhy.jpg
  - lib/image/ic_person.jpg
  - lib/image/image1.jpg
  - lib/image/image2.jpg
  - lib/image/image3.jpg
  - lib/image/image4.jpg
  - lib/image/image5.png
  - lib/image/jt.png











