name: yc_flutter_tool
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #添加网络请求依赖
  http: ^0.11.3+16
  dio : 3.0.9
  # provider
  provider: 4.0.0
  # 添加sharedPreference依赖
  shared_preferences: ^0.5.1
  # 添加文件依赖
  path_provider: ^0.5.0
  #添加Sqflite依赖
  sqflite: ^1.0.0
#  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/string/zh.json
    - assets/string/en.json
    - assets/string/pt.json
    - assets/string/ja.json
    - assets/image/ic_person.jpg
    - assets/image/image1.jpg
    - assets/image/image2.jpg
    - assets/image/image3.jpg
    - assets/image/image4.jpg
    - assets/image/image5.png